# Generated by Django 3.0.6 on 2021-05-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210526_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by_username', to='users.UserRegistrationModel'),
        ),
    ]
