# Generated by Django 3.0.6 on 2021-05-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210526_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationdetail',
            name='date_joined',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='userregistrationdetail',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
    ]
