# Generated by Django 3.0.6 on 2021-05-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210526_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationdetail',
            name='s_no',
        ),
    ]
