# Generated by Django 3.0.6 on 2021-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userregistrationdetail_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='role',
            field=models.CharField(choices=[('u', 'user'), ('a', 'admin')], default='user', max_length=20),
        ),
    ]
