# Generated by Django 3.0.6 on 2021-05-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210526_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationdetail',
            name='s_no',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserRegistrationModel'),
        ),
    ]
