# Generated by Django 3.0.6 on 2021-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userregistrationdetail_s_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationDetail',
            new_name='UserRegistrationDetail1',
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='is_active',
            field=models.CharField(choices=[('i', 'inactive'), ('a', 'active')], default='inactive', max_length=20),
        ),
    ]
