# Generated by Django 3.0.6 on 2021-05-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210526_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationDetail1',
        ),
    ]
