# Generated by Django 3.0.6 on 2021-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userregistrationdetail1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationDetail1',
            new_name='UserRegistrationDetail',
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='role',
            field=models.CharField(choices=[('0', 'user'), ('1', 'admin')], default='user', max_length=20),
        ),
    ]
