# Generated by Django 3.0.6 on 2021-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210526_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='is_active',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='inactive', max_length=20),
        ),
    ]
