# Generated by Django 3.0.6 on 2021-05-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210527_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationdetail',
            old_name='Address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='userregistrationdetail',
            old_name='Address2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='userregistrationdetail',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userregistrationdetail',
            old_name='Gender',
            new_name='gender',
        ),
    ]
