# Generated by Django 3.0.6 on 2021-05-28 08:05

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210527_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationBasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('0', 'user'), ('1', 'admin')], default='user', max_length=20)),
                ('is_active', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistrationExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('s_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserRegistrationBasicInformation')),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegistrationDetail',
        ),
        migrations.DeleteModel(
            name='UserRegistrationModel',
        ),
    ]
