# Generated by Django 3.0.6 on 2021-06-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210528_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistrationBasicInformation',
            new_name='UserRegistrationBasic',
        ),
        migrations.RenameModel(
            old_name='UserRegistrationExtraInformation',
            new_name='UserRegistrationExtra',
        ),
    ]
