# Generated by Django 3.0.6 on 2021-06-01 08:01

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210601_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', phone_field.models.PhoneField(max_length=31)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserRegistrationBasic',
            new_name='UserRegistrationModel',
        ),
        migrations.DeleteModel(
            name='UserRegistrationExtra',
        ),
        migrations.AddField(
            model_name='userregistrationdetailmodel',
            name='user_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserRegistrationModel'),
        ),
    ]
