# Generated by Django 3.0.6 on 2021-06-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210601_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationdetailmodel',
            old_name='user_detail_id',
            new_name='user_info',
        ),
    ]
