# Generated by Django 3.0.6 on 2021-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_flightmodel_userflightmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
