# Generated by Django 3.0.6 on 2021-06-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210602_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userflightmodel',
            old_name='flight_id',
            new_name='flight_info',
        ),
        migrations.RenameField(
            model_name='userflightmodel',
            old_name='user_id',
            new_name='user_info',
        ),
    ]
