# Generated by Django 3.0.6 on 2021-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210602_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflightmodel',
            name='date_of_booking',
            field=models.DateField(default=None),
        ),
    ]
