# Generated by Django 3.0.6 on 2021-06-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userflightmodel_date_of_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightmodel',
            name='is_active',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='FlightImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('flight_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FlightModel')),
            ],
        ),
    ]
