# Generated by Django 3.0.6 on 2021-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userflightmodel_date_of_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='x',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='is_active',
            field=models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='active', max_length=20),
        ),
    ]
