# Generated by Django 3.0.6 on 2021-06-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_flightimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='x',
        ),
    ]
