# Generated by Django 3.0.6 on 2021-06-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210610_0139'),
        ('users', '0030_delete_x'),
    ]

    operations = [
    ]
