# Generated by Django 3.0.6 on 2021-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userregistrationmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
